apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: unix@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-token
        selector:
          dnsZones:
            - '${SECRET_DOMAIN}'
            - '${SECRET_DOMAIN2}'
            - '${SECRET_DOMAIN3}'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${SECRET_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: ${SECRET_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-token
        selector:
          dnsZones:
            - '${SECRET_DOMAIN}'
            - '${SECRET_DOMAIN2}'
            - '${SECRET_DOMAIN3}'
