---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-creative-v1
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn
