---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-creative
  namespace: gaming
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft-bedrock
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: itzg/minecraft-bedrock-server
      tag: latest
      pullSecret: false
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      gameMode: creative
      maxPlayers: 20
      difficulty: peaceful
      serverName: EthanCreate
      ops: "2535460828971767"
      serviceType: LoadBalancer
      maxThreads: 16
      cheats: false
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-creative-v1

    serviceAnnotations:
      metallb.universe.tf/loadBalancerIPs: ${SVC_MC_ADDR}
