---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 2.14.4
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system

  values:

    replicaCount: 1
    image:
      repository: nextcloud
      tag: 24.0.1-apache
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN2}"
        external-dns/is-public: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
      path: /
      pathType: Prefix
      tls:
        - secretName: nextcloud-tls
          hosts:
            - "next.${SECRET_DOMAIN2}"

    nextcloud:
      host: next.${SECRET_DOMAIN2}
      username: admin
      password: ${SECRET_NEXTCLOUD}

      datadir: /var/www/html/data

      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array ('${SVC_INGRESS_ADDR}')
          );
        protocol.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https'
          );
        phone_region.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'US'
          );

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 100Gi
    nextcloudData:
      enabled: true
      storageClass: "managed-nfs-storage"
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
    rbac:
      enabled: true
