---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 2.14.4
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system

  values:

    replicaCount: 1
    image:
      repository: nextcloud
      tag: 24.0.1-apache
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN2}"
        external-dns/is-public: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
      path: /
      pathType: Prefix
      tls:
        - secretName: nextcloud-tls
          hosts:
            - "next.${SECRET_DOMAIN2}"

    nextcloud:
      host: next.${SECRET_DOMAIN2}
      username: admin
      password: ${SECRET_NEXTCLOUD}

      datadir: /var/www/html/data
      defaultConfigs:
        .htaccess: true
        apache-pretty-urls.config.php: true
        apcu.config.php: true
        apps.config.php: true
        autoconfig.php: false
        redis.config.php: false
        smtp.config.php: true
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwrite.cli.url' => 'https://nextcloud.${SECRET_DOMAIN}',
            'overwriteprotocol' => 'https',
            'filelocking.enabled' => 'true',
            'loglevel' => '2',
            'trusted_proxies' =>
              array(
                0 => '${NETWORK_K8S_CLUSTER_CIDR}',
                1 => '${NETWORK_K8S_SERVICE_CIDR}',
              )
          );

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 100Gi
    nextcloudData:
      enabled: true
      storageClass: "managed-nfs-storage"
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
    rbac:
      enabled: true
