kind: Secret
ansible_user: ENC[AES256_GCM,data:6FAiYQ==,iv:lkK7jTvukz4+sN/qhHwXks7qzPCQco6N3QbbqLNAK/8=,tag:D9cj9PcpDs+N10N0eOAfNQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:iVq00YR8DR33,iv:TIkpFJSAh2jC2PCO3+QzVBO1r8XsmJv+D4WHcr4FUCg=,tag:zlBbjGL9HaFuTC7YBHrwgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d3RHSW8zZGg4SEp3QmVy
            Y04vM2tEZThNdTlxL0ZCWnJTcE5NVHFPeVhvCkxJZ2lHT01SZk5TUGdONVhWb3hF
            MU5lZkQ0NGcycXdFRlFtNy9Xd0lFUkEKLS0tIEcrYUFGUWowQUF4NHo3djFRc3BN
            MFR4YkZ0elhVeWUxeGp4YTU2d2dJRzgK5eJexKMwi+eWuKIszDomvsYMc6pccWlw
            e7fXQBGzJ1r0WQA9TidwgIvqJ9wUhCTvCZxZh2rp6rPDkJp6yU6Omw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T02:44:53Z"
    mac: ENC[AES256_GCM,data:fEuEeXIt1/q90yIp9I69wjDx8Oql+zEZ7uC+edpzjOwOtp59fhGDDMfsIDn95KC/cSCze0BaEEYYJmuvXHfJMsNhPdew1Qb7eyicDJCCZWZ4Gmu2lanfSZ/HjuT/2il0U8awDqOoX9z5z/CwgJmqUO7+YXSbgJ5/A//S0SHkq1U=,iv:vAQbnCQ5rymT3VUrFZ3T5tvAy39YmTNbwr0AWJBkF/E=,tag:oQ/mnyN+lVMeXhix6/HQBw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
