kind: Secret
ansible_user: ENC[AES256_GCM,data:Tiz9mQ==,iv:NjJVBDS+Fdo74zpfmxCOnXI0GRTNmvbFbRYJzZNBZvs=,tag:X+YmQJwlLXuS5qyVXXsb3g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:yX2k/+lbuEA+,iv:eSwPGyeXkEMBP7QjEwXrPAdWPQd+IdXkAfVj/rMW9lY=,tag:b8uaoawSHw+bXAkCmuKxEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVnRjOE16WlcrcjFCTmJS
            REhMa2JkN3RMS280OFM1emdEdkdrYTlPY1JzCkdlSlpYYS9nTWJHL090STBHRmtr
            cWFVS1pBdEl0enBqa1VRcjYwd1poS0UKLS0tIDlSV3luVDBEUDRhVGRWWlBFVTBH
            bCt3aStMUW1CR1ZIT0RRS2tpd2JkRFkKT3eOVdohJfULnMwCgVmIGSGF0lZkHLgL
            al/5CKmFH7PvaKq+BaVmfiYn9+egyiU7tGs9K0KGMFnpX8YuL6CPpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T02:44:53Z"
    mac: ENC[AES256_GCM,data:c0efLv7JeBMBaYjgT5jnMGr8SKMlJ81e8BpV9Bzl6+GACkiaq84lYuhsK5n0Ro/4Y+HLjDvuiiFiLL5vhgCwOaY0xyUzJ0DafqhjueWl7uSZtaoJZnXzEVZGnA2drvaXCCNRJNsajwZsgpwA6eV3A70c+qSLHe5xyGuDE/12IB8=,iv:ORHbCs59YNK7rE6w27s6fZw5pBfNE5acIBf9AeyBxlo=,tag:lO2DcpuYDNxyBQHFkzwnog==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
