---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.8.1507
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "sonarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${INTERNAL_DOMAIN}"
          - secretName: sonarr-tls

#    podSecurityContext:
#      fsGroup: 0
#      supplementalGroups:
#        - 100

    persistence:

      config:
        enabled: true
        existingClaim: sonarr-config

      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/Media
        mountPath: /media

      media2:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS2_ADDR}"
            path: /volume1/Media2
        mountPath: /media2

      temp:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS1_ADDR}"
            path: /volume1/temp
        mountPath: /temp_dir

      backups:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS2_ADDR}"
            path: /volume1/Kubernetes/sonarr
        mountPath: /config/Backups

    resources:
      requests:
        memory: 1795M
        cpu: 10m
      limits:
        memory: 16G
        cpu: 8500m

    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.1.0
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: true
