---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.fairwinds.com/stable
      chart: goldilocks
      version: 6.1.4
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  values:

    uninstallVPA: false

    vpa:
      enabled: true

    metrics-server:
      enabled: false

    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.3.3
      pullPolicy: IfNotPresent

    controller:
      enabled: true
      resources:
        requests:
          cpu: 35m
          memory: 105M
        limits:
          cpu: 469m
          memory: 665M

    dashboard:
      enabled: true
      resources:
        requests:
          cpu: 35m
          memory: 105M
        limits:
          cpu: 150m
          memory: 665M

      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: goldilocks.${INTERNAL_DOMAIN}
            paths:
              - path: /
                type: ImplementationSpecific
        tls:
          - secretName: tls.goldilocks
            hosts:
              - goldilocks.${INTERNAL_DOMAIN}
