pipeline {
    agent any
    stages {
        stage('Run Update') {
            steps {
                ansiblePlaybook('../ansible/update.yml') {
                    inventoryPath('../ansible/hosts')
                    ansibleName('Maintenance Script')
                    tags('1, 2')
                    credentialsId('kube')
                    become(true)
                    becomeUser('root')
                    sudo(true)
                    sudoUser('root')
                    forks(forks = 5)
                    }
                }
            }
        }
    }
