pipeline {
    agent any

    parameters {
        string(name: 'environment', defaultValue: 'default', description: 'Workspace/environment file to use for deployment')
        string(name: 'version', defaultValue: '', description: 'Version variable to pass to Terraform')
        booleanParam(name: 'autoApprove', defaultValue: false, description: 'Automatically run apply after generating plan?')
    }
    
    environment {
        TF_IN_AUTOMATION      = '1'
    }

    stages {
        stage('Run Update') {
            steps {
                ansiblePlaybook('../ansible/update.yml') {
                    inventoryPath('../ansible/hosts')
                    ansibleName('Maintenance Script')
                    tags('1, 2')
                    credentialsId('kube')
                    become(true)
                    becomeUser('root')
                    sudo(true)
                    sudoUser('root')
                    forks(forks = 5)
                    unbufferedOutput(boolean unbufferedOutput = true)
                    colorizedOutput(boolean colorizedOutput = false)
                    hostKeyChecking(boolean hostKeyChecking = false)
                    additionalParameters(String params)
                    extraVars {
                        extraVar(String key, String value, boolean hidden)
                    }
                }
            
            }
        }
    }
}