pipeline {
    agent any
    stages {
        stage('Run Update') {
            steps {
                ansiblePlaybook credentialsId: 'ansible_sshkey', inventory: 'ansible/hosts', playbook: 'ansible/update.yml'
                }
            }
        }
    }
