apiVersion: v1
kind: Secret
metadata:
    name: external-dns
    namespace: external-dns
stringData:
    key: ENC[AES256_GCM,data:vYs/EMbQn0BRF+OEzuPyaXSmLA1D3MrTc1jJ9lqWW/8tYHWUHQ==,iv:lEKEMuNhRHd2HEc79iS3vP5kX3MPgDyzI4h9rUEz2Mo=,tag:E/GG+QRo8WHXIpAMri7PEA==,type:str]
    email: ENC[AES256_GCM,data:GM25+66493zVp1MYOjXxensv,iv:pvn/Ci2YvQljEtFgafZdBpwhi/4lWASVr61/Z5IzRbk=,tag:wdmRRBiiAEvuHMybC/CdnQ==,type:str]
    token: ENC[AES256_GCM,data:hjFPssfxP8FhezZTGFF2wjKrnyxbGWIWi+eayqIaOkxv6frrl2y10Q==,iv:ldsE6DZry67nX/7y8ub7sbgolP1+YqhuO6ao13axmRA=,tag:zvNnYjmP9kLfVf7u9FPaGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNS96eFRxSG5zZE52RGhs
            TnFLUmNucGtpSzZXM3lWV1JKQmJKNDhMK0RvCjU5UE1CUWlRMUFYS1p4dkJjaXV2
            Zm4yMTJzTDU4VnB5L2hEWGpxUWFPYWsKLS0tIFdTMlM0VTB4NFQrbDNySUYwWHhm
            WXk1aHlzNk0yUkZUK2xWV0pUYmpZbncK5fXKusl3qkMwFoudYi6SuiwP1x9zCNrR
            TmnTlQV7GaR/4N5lieEzSq+JMXNxetfsBO0+++MgvnOI0teuLDhQcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-20T16:25:37Z"
    mac: ENC[AES256_GCM,data:bxeM4VlbRpCUvswn6jTOVgs4RVKcc5zTXJRotXjdMFeCSliL4WXQjMLD1xaR1NIu4tAVngG/nw+ryqGE7qEkFIruoE2i1H1vV/U5Ctyr/zgxh6IXYf8yL4UqWy75Ip//0TZghwbDpV5gK9r8Lqfp219CxgSARQ2YBd9BfTeiEWg=,iv:4uXeNG+RJwXPyqtEExfS9ghcGkNZ2T29PnWd2qeeOsI=,tag:FUWDxPuIzlgGh+fU0oYuvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
