---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: k8s.gcr.io/external-dns/external-dns
      tag: v0.12.0
    interval: 5m
    logLevel: debug
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: email
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: key
    extraArgs:
      - --cloudflare-proxied
      - --annotation-filter=external-dns/is-public in (true)
    policy: sync
    sources:
      - ingress
    txtPrefix: "k8s."
    txtOwnerId: "default"
    domainFilters:
      - "${SECRET_DOMAIN}"
      - "${SECRET_DOMAIN2}"
      - "${SECRET_DOMAIN3}"
    resources:
      requests:
        memory: 105M
        cpu: 15m
      limits:
        memory: 200M
        cpu: 100m
