---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-lobby-v1
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
