---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.14.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured
        namespace: flux-system
  values:

    image:
      repository: weaveworks/kured
      tag: "1.9.2"
      pullPolicy: IfNotPresent
    updateStrategy: RollingUpdate
    configuration:
      timeZone: America/New_York
      startTime: 10am
      endTime: 12pm
    #  notifyUrl: ${KURED_DISCORD_WEBHOOK_URL}
      rebootCommand: "/usr/bin/systemctl reboot"
    metrics:
      create: true
