# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OXpIRjRSTmd1R2xpQ2xy
            eXlzYlJsMnFEN2VHZWRQMHo4Wk9pZDdsSHgwCndtQVdiNmJGUUNHZG9wbDRnalRk
            SStCMkljNkRSRzY4dVJQTnFxNndDNTgKLS0tIHkwcVcxS3ZyV2QwN1hxUlZBaTk1
            QjQ2bENvd29DMkNTMkphT1pNZVE1UUEKcDGTyTElUye0TwIukKiYZdY8BB5oy0Xs
            KPdb1M+1+i2MM9BJhslsneUMd/6g6f61PmTYA3hCUEghAg/S1TXqTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T02:44:53Z"
    mac: ENC[AES256_GCM,data:L/4Khd/5i/puG4XeaPFkDE6+8L3VNETOjwv/7+Kn7N/UUUPnSsrwu/NQhJjs92AG26ulPfxPHtd1Vurbn8iR+Mgf4hPueZ6Frxn5/3NWQG+RophqoUfAWd2LrqFN3HPuM56UI0mcOwQU3sc84N+9EWG1URNMW0RmIn+yCOJpYo4=,iv:qlWP2uNMAPQGHKALZagSUtOHRy27L2GJ43tj6sgqb80=,tag:JNN1VMsm3qZUBCsaqk8hsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
