---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elk
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.elastic.co
      chart: eck-operator
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: docker.elastic.co/eck/eck-operator
      tag: 2.3.0
      pullPolicy: IfNotPresent

    installCRDs: false
